require("config.lazy")
require("config.mason")
require("config.lspconfig")
-- require("config.theme.catppuccin")
require("config.theme.gruvbox")
-- require("config.theme.gruvbox-baby")
require("config.keymaps")
require("config.options")
require("config.lualine")
-- require("config.telescope")
